language: ruby
rvm:
  - 2.5.1
branches:
  only: [master, dev]
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
  - bundle exec rubocop -R
  - bundle exec rake test
sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler # caching bundler gem packages will speed up build
exclude: [vendor]
install:
- bundle install
