language: ruby
rvm:
  - 2.4.1

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
  
sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
exclude: [vendor]

install:
- bundle install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: dev